CREATE TABLE IF NOT EXISTS DATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    DATE DATE NOT NULL
);